### PR TITLE
add signin

### PR DESCRIPTION
**Pull request by erfanasadi**

### CODE REVIEW

**Comment by shyamtawli** [comment]
not a good design can you make it more attractive ?

**Comment by erfanasadi** [comment]
yes ,what can i do?
i think i can add a good background

**Comment by erfanasadi** [comment]
yes ,what can i do?
i think i can add a good background

**Comment by erfanasadi** [comment]
not good?

**Comment by shyamtawli** [comment]
let me send you a desgin
sig

**Comment by erfanasadi** [comment]
is this good?

**Comment by shyamtawli** [comment]
@erfanasadi nicely done but some fixing needed.
1. remove dolla logo from top.
2. add little margin in bottom of email and password label.
3. capital login to Login
4. add margin bottom to Login button.

**Comment by shyamtawli** [comment]
Nice that will be fine.

**Pull request merged**
